[project]
name = "autogen-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "autogen-ext>=0.7.4",
    "mlflow>=3.4.0",
]
